spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/scm2
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: admin
  

#emai configuration



